ruleset_version: '1.1'
engine_min_version: '>=2.8.0'
scope: individual
rules:
- name: test_claude_model
  scope: individual
  priority: 60
  conditions:
    claude_preference: model_name.startswith("claude")
  action: modify
  parameters:
    preferred_model: claude-3-sonnet
    explanation: User prefers Claude models
  parent_rule: null
  inherits_from: null
  description: Redirect to Claude models when requested
  enabled: true
  created_at: '2025-06-24T23:51:24.070982'
  updated_at: '2025-06-24T23:51:24.071005'
metadata: {}
