ruleset_version: "1.1"
engine_min_version: ">=2.8.0"
scope: individual
metadata:
  description: "Individual user-level rules and preferences"
  created_by: "user-system"
  created_at: "2025-01-20T00:00:00Z"
rules:
  - name: "user_preference_model"
    scope: individual
    priority: 40
    action: modify
    description: "Apply user's preferred model if available"
    enabled: true
    conditions:
      user_preferences: "user_preferred_model != null and user_preferred_model in available_models"
    parameters:
      preferred_model: "{{user_preferred_model}}"
      respect_user_choice: true

  - name: "user_daily_limit"
    scope: individual
    priority: 65
    action: deny
    description: "Enforce user's daily usage limits"
    enabled: true
    conditions:
      daily_usage: "daily_request_count >= user_daily_limit"
    parameters:
      error_message: "Daily usage limit reached"
      reset_time: "24:00:00"
      upgrade_suggestion: "Consider upgrading to increase limits"

  - name: "user_content_filter"
    scope: individual
    priority: 70
    action: deny
    description: "Apply user's content filtering preferences"
    enabled: true
    conditions:
      content_filter: "user_content_filter_enabled == true and content_matches_filter == true"
    parameters:
      filter_categories: "{{user_filter_categories}}"
      custom_keywords: "{{user_blocked_keywords}}"

  - name: "accessibility_features"
    scope: individual
    priority: 35
    action: modify
    description: "Apply accessibility preferences"
    enabled: true
    conditions:
      accessibility: "user_accessibility_enabled == true"
    parameters:
      font_size_multiplier: "{{user_font_size}}"
      high_contrast: "{{user_high_contrast}}"
      screen_reader_friendly: "{{user_screen_reader}}"

  - name: "personal_assistant_mode"
    scope: individual
    priority: 45
    action: modify
    description: "Customize responses for personal assistant use"
    enabled: true
    conditions:
      assistant_mode: "user_mode == 'personal_assistant'"
    parameters:
      response_style: "conversational"
      include_suggestions: true
      remember_context: true
      personalize_responses: true
    parent_rule: "user_preference_model"

  - name: "learning_mode"
    scope: individual
    priority: 30
    action: modify
    description: "Educational mode with detailed explanations"
    enabled: true
    conditions:
      learning: "user_mode == 'learning' or user_role == 'student'"
    parameters:
      explain_reasoning: true
      provide_examples: true
      suggest_resources: true
      step_by_step: true

  - name: "privacy_protection"
    scope: individual
    priority: 80
    action: validate
    description: "Protect user privacy based on preferences"
    enabled: true
    conditions:
      privacy: "user_privacy_level == 'strict'"
    parameters:
      anonymize_data: true
      disable_logging: true
      local_processing_preferred: true
      data_retention_days: 7