ruleset_version: "1.1"
engine_min_version: ">=2.8.0"
scope: project
metadata:
  description: "Project-level rules for specific applications or use cases"
  created_by: "project-admin"
  created_at: "2025-01-20T00:00:00Z"
rules:
  - name: "sensitive_project_restriction"
    scope: project
    priority: 85
    action: deny
    description: "Restrict access to sensitive projects"
    enabled: true
    conditions:
      project_classification: "project_id in ['classified', 'confidential', 'restricted']"
      user_clearance: "user_clearance_level < 3"
    parameters:
      error_message: "Insufficient clearance for this project"
      required_clearance: 3

  - name: "development_environment_rules"
    scope: project
    priority: 70
    action: modify
    description: "Apply development environment specific rules"
    enabled: true
    conditions:
      environment: "environment == 'development'"
    parameters:
      enable_debug_mode: true
      log_level: "DEBUG"
      disable_caching: true

  - name: "production_safety_checks"
    scope: project
    priority: 75
    action: validate
    description: "Additional validation for production environments"
    enabled: true
    conditions:
      environment: "environment == 'production'"
    parameters:
      require_approval: true
      enable_audit_logging: true
      max_request_size: 1048576  # 1MB

  - name: "cost_optimization"
    scope: project
    priority: 60
    action: modify
    description: "Apply cost optimization strategies"
    enabled: true
    conditions:
      cost_tier: "project_cost_tier == 'budget'"
    parameters:
      max_tokens: 2000
      preferred_models: ["gpt-3.5-turbo", "claude-haiku"]
      enable_caching: true

  - name: "team_collaboration_rules"
    scope: project
    priority: 55
    action: allow
    description: "Rules for team collaboration features"
    enabled: true
    conditions:
      team_access: "user_id in project_team_members"
    parameters:
      enable_sharing: true
      enable_comments: true
      enable_history: true
    inherits_from: ["default_allow"]